modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/Frefreak/mc_the_toolkits/issues"

[[mods]]
modId="the_toolkits"
version="${file.jarVersion}"
displayName="The Toolkits"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/Frefreak/mc_the_toolkits"
# TODO
#logoFile="examplemod.png" #optional
description='''
A mod providing various utilities to inspect the internal of game objects
(blocks, items, world...)
'''
[[dependencies.the_toolkits]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.the_toolkits]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraftVersionRange}"
    ordering="NONE"
    side="BOTH"
