name: Build and Release

on:
  push:
    branches:
      - 1.16.5
      - 1.18.2
      - "1.19"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build --scan

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-libs
          path: build/libs/*.jar

      - name: Set release date and time
        run: |
          echo "RELEASE_DATETIME=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }} - ${{ env.RELEASE_DATETIME }}
          draft: false
          prerelease: false

      - name: Upload all JAR files as Release Assets
        run: |
          for jar_file in build/libs/*.jar; do
            asset_name=$(basename "$jar_file")
            echo "Uploading $asset_name"
            curl \
              --progress-bar \
              --location \
              --request POST \
              --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              --header "Content-Type: $(file -b --mime-type "$jar_file")" \
              --upload-file "$jar_file" \
              --url "${{ steps.create_release.outputs.upload_url }}?name=$asset_name"
          done
