name: Build and Release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [1.19, 1.18.2, 1.16.5]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Run Gradle build
        run: ./gradlew build

      - name: Create GitHub release and upload JAR files
        uses: Roang-zero1/github-create-release-action@v3
        with:
          version_regex: .*
          files: 'build/libs/*.jar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
